USE ItRental

CREATE TABLE Renters (
	RenterId INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(MAX) NOT NULL,
	RenterLevel INT NOT NULL
);

INSERT INTO Renters
VALUES ('Maren', 3)
INSERT INTO Renters
VALUES ('Kaare', 5)
INSERT INTO Renters
VALUES ('Nicklas', 8)
INSERT INTO Renters
VALUES ('Nickolai', 3)
INSERT INTO Renters
VALUES ('Asger', 5)

CREATE TABLE Rentals (
	RentalId INT PRIMARY KEY IDENTITY(1,1),
	RentalTime DATETIME2(0) NOT NULL,
	ReturnTime DATETIME2(0) NOT NULL,
	EquipmentId INT NOT NULL FOREIGN KEY REFERENCES Equipments(EquipmentId),
	Units INT NOT NULL,
	RenterId INT NOT NULL FOREIGN KEY REFERENCES Renters(RenterId)
);

INSERT INTO Rentals
VALUES (DATEADD(DAY, -50, CURRENT_TIMESTAMP), DATEADD(DAY, -10, CURRENT_TIMESTAMP), 1, 2, 1)
INSERT INTO Rentals
VALUES (DATEADD(DAY, -40, CURRENT_TIMESTAMP), DATEADD(DAY, 5, CURRENT_TIMESTAMP), 2, 1, 2)
INSERT INTO Rentals
VALUES (DATEADD(DAY, -30, CURRENT_TIMESTAMP), DATEADD(DAY, -5, CURRENT_TIMESTAMP), 3, 1, 5)
INSERT INTO Rentals
VALUES (DATEADD(DAY, -20, CURRENT_TIMESTAMP), DATEADD(DAY, 15, CURRENT_TIMESTAMP), 4, 1, 4)
INSERT INTO Rentals
VALUES (DATEADD(DAY, -10, CURRENT_TIMESTAMP), DATEADD(DAY, 30, CURRENT_TIMESTAMP), 5, 3, 3)
INSERT INTO Rentals
VALUES (CURRENT_TIMESTAMP, DATEADD(DAY, 50, CURRENT_TIMESTAMP), 6, 1, 1)